### ISSUE TITLE
"Mosh is a replacement for ssh"

### ISSUE THREAD

**Issue by cgull** [mobile-shell/moshweb#32]
It's not a complete replacement at all, it's a virtual terminal that happens to have network magic inside the box...

This is illuminating:

http://www.mail-archive.com/git@vger.kernel.org/msg68620.html

I think that if Mosh's capabilities were clearer here it might save a lot of confusion.  This might apply to man pages and README as well.

**Comment by andersk** [comment]
Addressed by #45, I think.
