### ISSUE TITLE
that screenshot on the main page...

### ISSUE THREAD

**Issue by mighty9245** [mobile-shell/moshweb#59]
hey, you have a screenshot on your main page, this one:
![](https://mosh.org/mosh.png)

i know, it's almost a decade old, but i really want to know: what are these colors? what is this color scheme? i tried searching for it using color codes from the screenshot, but with no luck :(
it came with @keithw initial (!) commit back in 2012, so i guess it'll be a good idea to ask him about it: do you know/remember something about this environment?

sorry for disturbing you with this issue, which isn't actually an issue, but i hope i'm not the one who likes these colors ;) feel free to close this issue if you want.

**Comment by keithw** [comment]
If I remember correctly, I took a screenshot and then bumped up the saturation manually in the GIMP. Sorry to disappoint. But can't you just eye-dropper these colors and then make a theme yourself? There's no anti-aliasing here so you are getting the real colors on each pixel. :-)

**Comment by mighty9245** [comment]
@keithw, what a quick response, thank you! that's really disappointing :( well, i'll take a look, what i can do having only several colors.
