### ISSUE TITLE
[ UI Problem ] Div not centered in the mobile version

### ISSUE THREAD

**Issue by tansionline** [mobile-shell/moshweb#63]
![mobile-version](https://user-images.githubusercontent.com/41347478/129141124-e9700156-92e6-4b86-b528-20495a2f1700.PNG)

**Comment by eminence** [comment]
Fix should be deployed now.  Thanks for the report and for the fix

**Comment by tansionline** [comment]
Your welcome. BTW you guys did a wonderful job. 
Stay Safe

![](https://media.giphy.com/media/Gv5Fh0GIEffdn8DsKs/giphy.gif)
