### ISSUE TITLE
"403 Forbidden" on https://mosh.org/

### ISSUE THREAD

**Issue by CyberShadow** [mobile-shell/moshweb#72]
[mosh.org](https://mosh.org/) currently displays:

> Forbidden
>
> You don't have permission to access / on this server.

https://downforeveryoneorjustme.com/mosh.org says mosh.org is down.

**Comment by eminence** [comment]
Thanks for the report.  Apparently there is some flooding in the a building that contains the storage servers for mosh.org.

**Comment by CyberShadow** [comment]
That's nuts. Hope everyone is OK.
